cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//src:color",
        "//src:hittable_list",
        "//src:ray",
        "//src:rtweekend",
        "//src:sphere",
        "//src:vec",
    ],
)
